/*
  # Blog ve Anket Sonuçları Tabloları

  1. Yeni Tablolar
    - `blog_posts`: Blog yazıları için
      - `id` (int8, primary key)
      - `title` (text): Yazı başlığı
      - `content` (text): Yazı içeriği
      - `excerpt` (text): Kısa özet
      - `image_url` (text): Kapak görseli URL'i
      - `created_at` (timestamptz): Oluşturulma tarihi
      - `updated_at` (timestamptz): Güncellenme tarihi

    - `survey_results`: Anket sonuçları için
      - `id` (int8, primary key)
      - `title` (text): Anket başlığı
      - `description` (text): Anket açıklaması
      - `image_url` (text): Kapak görseli URL'i
      - `data` (jsonb): Anket sonuç verileri
      - `created_at` (timestamptz): Oluşturulma tarihi
      - `updated_at` (timestamptz): Güncellenme tarihi

  2. Güvenlik
    - Her iki tablo için RLS aktif
    - Okuma politikaları herkese açık
    - Yazma politikaları sadece yetkilendirilmiş kullanıcılara açık
*/

-- Blog Posts Tablosu
CREATE TABLE blog_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  excerpt text NOT NULL,
  image_url text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Survey Results Tablosu
CREATE TABLE survey_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  image_url text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- RLS Aktivasyonu
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE survey_results ENABLE ROW LEVEL SECURITY;

-- Okuma Politikaları
CREATE POLICY "Blog posts are viewable by everyone"
  ON blog_posts
  FOR SELECT
  USING (true);

CREATE POLICY "Survey results are viewable by everyone"
  ON survey_results
  FOR SELECT
  USING (true);

-- Yazma Politikaları
CREATE POLICY "Blog posts can be created by authenticated users only"
  ON blog_posts
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Survey results can be created by authenticated users only"
  ON survey_results
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Güncelleme Politikaları
CREATE POLICY "Blog posts can be updated by authenticated users only"
  ON blog_posts
  FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Survey results can be updated by authenticated users only"
  ON survey_results
  FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');